
from building import *
import rtconfig

cwd = GetCurrentDir()

src = Glob('*.c')
path = [cwd]

LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'

group = DefineGroup('fireware_update_buf', src, depend = ['BSP_USING_COE_FOE_IO'], CPPPATH = path, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
