
from building import *
import rtconfig

cwd = GetCurrentDir()

src = []
src += Glob('*.c')

path = [cwd]
path += ['/inc']

LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'

CPPDEFINES = ['BSP_CFG_RTOS=2']

group = DefineGroup('usb_pcdc', src, depend = [], CPPPATH = path, LOCAL_CFLAGS = LOCAL_CFLAGS, CPPDEFINES=CPPDEFINES)

Return('group')
