
from building import *
import rtconfig

cwd = GetCurrentDir()

src = []

src += Glob('beckhoff/Src/*.c')
src += Glob('renesas/*.c')
src += Glob('*.c')

path    = [cwd]
path   += [cwd + '/beckhoff/Src']
path   += [cwd + '/renesas']

LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'

CPPDEFINES = ['ETHERCAT_SSC_PORT_GMAC_MDIO_SUPPORT=1', 'UM_ETHER_NETIF_FEATURE_R_ETHER_INSTANCE_EOE_VETHER=1']

group = DefineGroup('ethercat_eoe', src, depend = ['BSP_USING_ETHERCAT_EOE'], CPPPATH = path, LOCAL_CFLAGS = LOCAL_CFLAGS, CPPDEFINES=CPPDEFINES)

Return('group')
