/* generated configuration header file - do not edit */
#ifndef R_SCI_SPI_CFG_H_
#define R_SCI_SPI_CFG_H_
#define SCI_SPI_CFG_DMAC_SUPPORT_ENABLE (0)
#define SCI_SPI_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define SCI_SPI_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if SCI_SPI_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define SCI_SPI_CFG_MULTIPLEX_INTERRUPT_ENABLE         BSP_INTERRUPT_ENABLE
 #define SCI_SPI_CFG_MULTIPLEX_INTERRUPT_DISABLE        BSP_INTERRUPT_DISABLE
#else
 #define SCI_SPI_CFG_MULTIPLEX_INTERRUPT_ENABLE
 #define SCI_SPI_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_SCI_SPI_CFG_H_ */
